name: integration_sites_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - r-base=4.2
  - samtools
  - bedtools
  - bioconductor-biostrings
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-chipseeker
  - bioconductor-txdb.hsapiens.ucsc.hg38.knownGene
  - bioconductor-org.hs.eg.db
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - r-ggplot2
  - r-dplyr
  - r-data.table
  - r-ineq
  - r-vegan
  - r-seqlogo
  - r-optparse
  - r-rmarkdown
  - r-knitr
  - meme  # optional
